### ISSUE TITLE
Strange issues with PID 

### ISSUE THREAD

**Issue by falOn-Dev** [BroncBotz3481/YAGSL#33]
My team updated our swerve code to the next-gen update, and despite not changing our PID values, our driving seems to be completely shot. It drives in weird jerky motions and wrong directions, as well as continuing to jerk around when the joystick isn't being touched. I've attached a video of it before the update, and two after (one of motion and one of attempted standstill)

https://github.com/BroncBotz3481/YAGSL/assets/47285315/156bb3c7-2634-4cfc-addf-d296d12ddbc5

https://github.com/BroncBotz3481/YAGSL/assets/47285315/aaa7759e-00da-42a6-bb20-749236a2ac29

https://github.com/BroncBotz3481/YAGSL/assets/47285315/d2148ae0-5479-431f-a49c-c155f1f2979e

**Comment by falOn-Dev** [comment]
To clarify the order of the videos is, attempted standstill, attempted straight line, and pre-update

**Comment by Technologyman00** [comment]
Can you link your code?

**Comment by falOn-Dev** [comment]
https://github.com/Team2537/2024Crescendo

The old code is in main, the new code is in the branch labeled for issue 10
